spring:
  application:
    name: user-crud
  datasource:
    url: jdbc:mysql://localhost:3306/usercrud
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false